# Generated by Django 5.1.3 on 2025-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Type'),
        ),
    ]
