# Generated by Django 5.1.3 on 2025-02-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number from the supplier.', max_length=100, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('start_reading', models.FloatField(help_text='Reading at the start of the billing period.', verbose_name='Start Reading')),
                ('end_reading', models.FloatField(help_text='Reading at the end of the billing period.', verbose_name='End Reading')),
                ('fixed_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fixed Costs (€)')),
                ('variable_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Variable Costs (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Fixed + Variable Costs', max_digits=10, verbose_name='Total Amount (€)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT percentage applied to the total amount.', max_digits=5, verbose_name='VAT Rate (%)')),
                ('invoice_pdf', models.FileField(blank=True, help_text='Upload the original invoice as a PDF.', null=True, upload_to='expenses/invoices/', verbose_name='Invoice PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meter', models.ForeignKey(help_text='The main meter associated with this expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='meters.meter', verbose_name='Billed Meter')),
                ('supplier', models.ForeignKey(blank=True, help_text='The supplier who issued this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
        ),
    ]
