# Generated by Django 5.1.3 on 2024-12-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(verbose_name='Conversion Factor')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('from_consumption_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_from', to='meters.consumptiontype', verbose_name='From Consumption Type')),
                ('to_consumption_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_to', to='meters.consumptiontype', verbose_name='To Consumption Type')),
            ],
        ),
    ]
