# Generated by Django 5.1.3 on 2025-03-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_reading',
            field=models.ForeignKey(help_text='Reference to the actual meter reading at the end of the billing period.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_end', to='meters.meterreading', verbose_name='End Reading'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_reading',
            field=models.ForeignKey(help_text='Reference to the actual meter reading at the start of the billing period.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_start', to='meters.meterreading', verbose_name='Start Reading'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Fixed + Variable Costs, incl. VAT', max_digits=10, verbose_name='Total Amount (€)'),
        ),
    ]
