# Generated by Django 5.1.3 on 2024-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_meter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True, verbose_name='Short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meter',
            name='location_description',
            field=models.TextField(blank=True, null=True, verbose_name='Where to find this meter?2'),
        ),
    ]
