# Generated by Django 5.1.3 on 2024-12-03 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_meter_name_alter_meter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='deinstall_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deinstallation Date'),
        ),
        migrations.AddField(
            model_name='meter',
            name='install_date',
            field=models.DateField(default=datetime.date(2013, 1, 1), verbose_name='Installation Date'),
        ),
    ]
