# Generated by Django 5.1.3 on 2025-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_meter_deinstall_date_meter_install_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='name',
        ),
        migrations.AddField(
            model_name='meter',
            name='label',
            field=models.CharField(default='none', max_length=100, unique=True, verbose_name='Display Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meter',
            name='location_description',
            field=models.TextField(blank=True, null=True, verbose_name='Location Description'),
        ),
    ]
