# Generated by Django 5.1.3 on 2025-02-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_remove_meter_name_meter_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Reading Date')),
                ('value', models.FloatField(verbose_name='Meter Reading Value')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meter_readings/', verbose_name='Reading Photo')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter', verbose_name='Meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Read By')),
            ],
        ),
    ]
